version: '3'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: 'laravel'
      MYSQL_USER: 'laravel'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
  php:
    build:
        dockerfile: Dockerfile
    restart: on-failure
    command: 'sh /app/system/bootstrap.sh'
    volumes:
        - .:/app
    ports:
        - 8000:8000
    depends_on:
      - mysql